-- 코드를 입력하세요

    SELECT PRODUCT_CODE, SUM(price*sales_amount) AS SALES
    FROM PRODUCT, OFFLINE_SALE
    WHERE PRODUCT.PRODUCT_ID=OFFLINE_SALE.PRODUCT_ID
    GROUP BY PRODUCT.PRODUCT_CODE
    ORDER BY SALES DESC, PRODUCT_CODE ASC